version: '3.1'

services:

  some-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: jay
      MYSQL_DATABASE: BucketList

  my-running-app:
    depends_on:
      - some-mysql
    build: .
    image: my-running-app
    links:
      - some-mysql
    ports:
      - 5000:5000

